### ISSUE TITLE
👐🏽 Usage in a composite action

### ISSUE THREAD

**Issue by RobinTail** [ryoppippi/bunpare#8]
Dear @ryoppippi ,

I used your tool to make another tool — a composite GitHub action that writes a formatted comment into a pull request.
And I'd like to thank you for creating `bunpare` and share it with you so that maybe it could be useful for you too.
https://github.com/RobinTail/bun-diff-action

![image](https://github.com/user-attachments/assets/3b1c031e-d8e1-4ec0-b7ee-6ad3f6305f21)

There is no issue — just telling you that you made a great tool and I'm thankful for that ❤️

**Comment by ryoppippi** [comment]
@RobinTail nice!
Thank you for let me know!
I'm happy to hear that. 

I'll check it out and use it!

Cheers
